name: mad_devs
networks:
  dev:


services:
  # region --------------- APPS -------------


  user.api:
     container_name: user.api
     build:
       context: ./src/apps
       dockerfile: Dockerfile
     depends_on:
       - postgres.db
     restart: unless-stopped
     networks:
       - dev
  # end --------------------------------------

  # end --------------------------------------

  # region --------------- DB ----------------

  postgres.db:
    image: postgres:17.2-alpine
    container_name: postgres.db
    restart: unless-stopped
    networks:
      - dev
# end ---------------------------------------